# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [feature/*]
  pull_request:
    branches: [feature/*]

jobs:
  build-ios-debug:
    runs-on: macos-latest
    if: ${{ !contains(github.event.pull_request.title, '[Skip CI]') }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Prepare firebase config
        run: make secret
        env:
          FILE_FIREBASE_IOS_DEV: ${{ secrets.FILE_FIREBASE_IOS_DEVELOPMENT }}
          FILE_FIREBASE_IOS_PROD: ${{ secrets.FILE_FIREBASE_IOS_DEVELOPMENT }}
          FILE_FIREBASE_ANDROID_DEV: ${{ secrets.FILE_FIREBASE_ANDROID_DEVELOPMENT }}
          FILE_FIREBASE_ANDROID_PROD: ${{ secrets.FILE_FIREBASE_ANDROID_DEVELOPMENT }}
          SECRET_TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY_DEV }}
          SECRET_TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET_DEV }}
          FILE_FIREBASE_OPTION: ${{ secrets.FILE_FIREBASE_OPTION }}
          FILE_IOS_FIREBASE_APP_ID_FILE: ${{ secrets.FILE_IOS_FIREBASE_APP_ID_FILE }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.1"
      - run: flutter pub get
      - name: Run iOS
        run: flutter build ios --debug --no-codesign --flavor dev --target lib/main_dev.dart
  build-android-debug:
    runs-on: macos-latest
    if: ${{ !contains(github.event.pull_request.title, '[Skip CI]') }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Prepare firebase config
        run: make secret
        env:
          FILE_FIREBASE_IOS_DEV: ${{ secrets.FILE_FIREBASE_IOS_DEVELOPMENT }}
          FILE_FIREBASE_IOS_PROD: ${{ secrets.FILE_FIREBASE_IOS_DEVELOPMENT }}
          FILE_FIREBASE_ANDROID_DEV: ${{ secrets.FILE_FIREBASE_ANDROID_DEVELOPMENT }}
          FILE_FIREBASE_ANDROID_PROD: ${{ secrets.FILE_FIREBASE_ANDROID_DEVELOPMENT }}
          SECRET_TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY_DEV }}
          SECRET_TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET_DEV }}
          FILE_FIREBASE_OPTION: ${{ secrets.FILE_FIREBASE_OPTION }}
          FILE_IOS_FIREBASE_APP_ID_FILE: ${{ secrets.FILE_IOS_FIREBASE_APP_ID_FILE }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.1"
      - run: flutter pub get
      - run: flutter build apk --debug --flavor dev --target lib/main_dev.dart
  test:
    runs-on: macos-latest
    if: ${{ !contains(github.event.pull_request.title, '[Skip CI]') }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.1"
      - run: make secret
      - run: flutter pub get
      - run: flutter test
  codegen:
    runs-on: macos-latest
    if: ${{ !contains(github.event.pull_request.title, '[Skip CI]') }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.1"
      - run: make secret
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: git diff --quiet --exit-code
