name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main, feature/*]

jobs:
  ios-upload-testflight-prod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Prepare firebase config
        run: make secret
        env:
          FILE_FIREBASE_ANDROID_DEV: ${{ secrets.FILE_FIREBASE_ANDROID_DEVELOPMENT }}
          FILE_FIREBASE_ANDROID_PROD: ${{ secrets.FILE_FIREBASE_ANDROID_PRODUCTION }}
          SECRET_TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY_PROD }}
          SECRET_TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET_PROD }}
          FILE_FIREBASE_OPTION: ${{ secrets.FILE_FIREBASE_OPTION_PROD }}
          FILE_IOS_FIREBASE_APP_ID_FILE: ${{ secrets.FILE_IOS_FIREBASE_APP_ID_FILE_PROD }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.1"
      - run: flutter pub get
      - name: Set Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n ${{ secrets.FILE_PROVISIONING_PROFILE_PROD }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/In100Days.AppStore.mobileprovision
      # workaround step. it is not copy when flutter build ipa -> xcodebuild. it is defined build phases on xcode.
      - name: distribution cert codesign
        uses: bannzai/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.FILE_P12_KEY }}
          p12-password: ${{ secrets.P12_KEY_PASSWORD }}
          keychain: temp
          create-keychain: true
      - name: Create ipa
        run: |
          echo -n ${{ secrets.IOS_EXPORT_OPTIONS_PLIST_PROD }} | base64 -d > $(pwd -P)/ExportOptions.plist
          flutter build ipa --flavor prod --target lib/main_prod.dart --export-options-plist=$(pwd -P)/ExportOptions.plist --build-number ${GITHUB_RUN_NUMBER}
      - name: Upload to AppStoreConnect
        run: xcrun altool --upload-app --type ios -f "./build/ios/ipa/100日後に.ipa" -u "${{ secrets.IOS_APPLE_ID }}" -p "${{ secrets.IN100DAYS_APPLE_APP_PASSWORD }}"
  android-upload-googleplay-prod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Prepare firebase config
        run: |
          export ANDROID_KEYSTORE_PATH=$(pwd -P)/android/release.jks
          make secret
        env:
          FILE_FIREBASE_ANDROID_DEV: ${{ secrets.FILE_FIREBASE_ANDROID_DEVELOPMENT }}
          FILE_FIREBASE_ANDROID_PROD: ${{ secrets.FILE_FIREBASE_ANDROID_PRODUCTION }}
          SECRET_TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY_PROD }}
          SECRET_TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET_PROD }}
          FILE_FIREBASE_OPTION: ${{ secrets.FILE_FIREBASE_OPTION_PROD }}
          FILE_IOS_FIREBASE_APP_ID_FILE: ${{ secrets.FILE_IOS_FIREBASE_APP_ID_FILE_PROD }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
      - name: Prepare service account json
        run: echo -n ${{ secrets.ANDROID_GOOGLE_SERVICE_ACCOUNT_JSON }} | base64 -d > android/service-account.json
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.1"
      - run: flutter pub get
      - name: Prepare keystore file
        run: echo -n ${{ secrets.ANDROID_KEYSTORE_FILE }} | base64 -d > android/release.jks
      - run: flutter build appbundle --release --flavor prod --target lib/main_prod.dart --build-number ${GITHUB_RUN_NUMBER}
      - uses: r0adkll/upload-google-play@v1.0.16
        with:
          serviceAccountJson: android/service-account.json
          packageName: com.bannzai.in100days
          releaseFiles: build/app/outputs/bundle/prodRelease/app-prod-release.aab
          status: draft
          track: internal
